{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "lines_counter",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * from lines_counter;\n" }
   ]
  },
  {
   "title": "words_counter_batch",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * from words_counter_batch;\n"
    }
   ]
  },
  {
   "title": "new file in last week",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT count(*)\nFROM words_counter_batch\nwhere date between date_sub(now(),INTERVAL 1 WEEK) and now();",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "words-counter-batch",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "top_5_words_count",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT * FROM words_counter_batch ORDER BY AmountOfWords DESC LIMIT 5\n"
    }
   ]
  },
  {
   "title": "script-logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "top_5_lines_count",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM lines_counter ORDER BY LinesCount DESC LIMIT 5"
    }
   ]
  }
 ]
}