name: 'CD'     
on: push 
jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'

    - name: Get repositories
      uses: hiberbee/github-action-helm@1.5.0
      with:
        helm: repo list
        repository-config: repositories.yaml

    - name: Grafana chart
      run: helm grafana
      working-directory: charts/grafana

    - name: Install release
      uses: hiberbee/github-action-helm@latest
      with:
        helm: upgrade --install grafana charts/grafana