name: 'CD'     
on: push 
jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    
    - name: 'Helm repo add & update'
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add elastic https://helm.elastic.co
        helm repo update
    
    - name: 'Helm upgrade'
      run: |
        helm upgrade -n monitoring -i grafana grafana/grafana -f grafana/values.yaml
        helm upgrade -i elasticsearch elastic/elasticsearch -f elasticsearch/values.yaml 